version: '3.8'

volumes:
  pgdata:

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.development.env'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    restart: on-failure
    env_file:
      - '.development.env'
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data