version: '3.8'

volumes:
  pgdata:
  redis-cache-data:

services:
#  main:
#    container_name: main
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    env_file:
#      - '.env.development'
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - '${APP_PORT}:${APP_PORT}'
#    depends_on:
#      - postgres
#      - redis-cache
#    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    restart: on-failure
    env_file:
      - '.env.development'
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis-cache:
    image: redis:6
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-cache-data:/data